import './globals.scss';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ClientFooter from './footer';
import ClientNavbar from './nav';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'NetLogo User Manual',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <ClientNavbar />
        {children}
        <ClientFooter />
        <script>
          {`if (window.location.hash) {
            const target = document.querySelector(window.location.hash);
            if (target) {
              target.scrollIntoView({ behavior: 'smooth' });
              // Ensure the target is visible after scrolling
              setTimeout(() => {
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
              }, 100);
            }
          }`}
        </script>
      </body>
    </html>
  );
}
