/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Specifies a limit of returned records */
                    limit?: number;
                    /** @description Page number */
                    page?: number;
                    /** @description Filter by event type */
                    type?: string;
                    /** @description Filter by resource type */
                    resourceType?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Total number of items
                             * @example 5
                             */
                            count: number;
                            /**
                             * @description Number of items per page
                             * @example 10
                             */
                            limit: number;
                            /**
                             * @description Page number
                             * @example 0
                             */
                            page: number;
                            data: unknown[];
                        } & {
                            data: {
                                /** Format: uuid */
                                id: string;
                                type: string;
                                actorId: string;
                                resourceType: string;
                                resourceId: string;
                                payload: {
                                    [key: string]: unknown;
                                };
                                /** Format: date-time */
                                createdAt: string;
                                processedAt: string | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Entity's id
                             * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                             */
                            id: string;
                        } & {
                            filename: string;
                            contentType: string;
                            sizeBytes: number;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Specifies a limit of returned records */
                    limit?: number;
                    /** @description Page number */
                    page?: number;
                    visibility?: "public" | "private" | "unlisted";
                    tag?: string;
                    authorId?: string;
                    parentModelId?: string;
                    isEndorsed?: boolean;
                    keyword?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Total number of items
                             * @example 5
                             */
                            count: number;
                            /**
                             * @description Number of items per page
                             * @example 10
                             */
                            limit: number;
                            /**
                             * @description Page number
                             * @example 0
                             */
                            page: number;
                            data: unknown[];
                        } & {
                            data: (({
                                /**
                                 * Format: uuid
                                 * @description Entity's id
                                 * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                                 */
                                id: string;
                            } & {
                                /**
                                 * @description Entity creation date
                                 * @example 2020-11-24T17:43:15.970Z
                                 */
                                createdAt: string;
                                /**
                                 * @description Entity last update date
                                 * @example 2020-11-24T17:43:15.970Z
                                 */
                                updatedAt: string;
                            }) & {
                                latestVersionId: string | null;
                                parentModelId: string | null;
                                parentVersionId: string | null;
                                /** @description public | private | unlisted */
                                visibility: string;
                                isEndorsed: boolean;
                            })[];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Model title */
                        title: string;
                        /** @description Model description */
                        description?: string;
                        visibility?: "public" | "private" | "unlisted";
                        /** Format: uuid */
                        parentModelId?: string;
                        /** Format: uuid */
                        parentVersionId?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Entity's id
                             * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                             */
                            id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": ({
                            /**
                             * Format: uuid
                             * @description Entity's id
                             * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                             */
                            id: string;
                        } & {
                            /**
                             * @description Entity creation date
                             * @example 2020-11-24T17:43:15.970Z
                             */
                            createdAt: string;
                            /**
                             * @description Entity last update date
                             * @example 2020-11-24T17:43:15.970Z
                             */
                            updatedAt: string;
                        }) & {
                            latestVersionId: string | null;
                            parentModelId: string | null;
                            parentVersionId: string | null;
                            /** @description public | private | unlisted */
                            visibility: string;
                            isEndorsed: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        visibility?: "public" | "private" | "unlisted";
                        isEndorsed?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/models/{id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Specifies a limit of returned records */
                    limit?: number;
                    /** @description Page number */
                    page?: number;
                    visibility?: "public" | "private" | "unlisted";
                    tag?: string;
                    authorId?: string;
                    parentModelId?: string;
                    isEndorsed?: boolean;
                    keyword?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Total number of items
                             * @example 5
                             */
                            count: number;
                            /**
                             * @description Number of items per page
                             * @example 10
                             */
                            limit: number;
                            /**
                             * @description Page number
                             * @example 0
                             */
                            page: number;
                            data: unknown[];
                        } & {
                            data: (({
                                /**
                                 * Format: uuid
                                 * @description Entity's id
                                 * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                                 */
                                id: string;
                            } & {
                                /**
                                 * @description Entity creation date
                                 * @example 2020-11-24T17:43:15.970Z
                                 */
                                createdAt: string;
                                /**
                                 * @description Entity last update date
                                 * @example 2020-11-24T17:43:15.970Z
                                 */
                                updatedAt: string;
                            }) & {
                                latestVersionId: string | null;
                                parentModelId: string | null;
                                parentVersionId: string | null;
                                /** @description public | private | unlisted */
                                visibility: string;
                                isEndorsed: boolean;
                            })[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/additional-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    taggedVersionId?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": ({
                            /**
                             * Format: uuid
                             * @description Entity's id
                             * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                             */
                            id: string;
                        } & {
                            /** Format: uuid */
                            modelId: string;
                            /** Format: uuid */
                            taggedVersionId: string;
                            /** Format: uuid */
                            fileId: string;
                            filename: string;
                            contentType: string;
                            sizeBytes: number;
                            /** Format: date-time */
                            createdAt: string;
                        })[];
                    };
                };
            };
        };
        put?: never;
        /** @description Upload an additional file for a model. The file is sent as multipart/form-data with the file field named "file". */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Entity's id
                             * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                             */
                            id: string;
                        } & {
                            /** Format: uuid */
                            modelId: string;
                            /** Format: uuid */
                            taggedVersionId: string;
                            /** Format: uuid */
                            fileId: string;
                            filename: string;
                            contentType: string;
                            sizeBytes: number;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/additional-files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    fileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            modelId: string;
                            /** Format: uuid */
                            userId: string;
                            /** @description owner | contributor */
                            role: string;
                            /**
                             * @description Author assignment date
                             * @example 2020-11-24T17:43:15.970Z
                             */
                            createdAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description User to add as contributor
                         */
                        userId: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            modelId: string;
                            /** Format: uuid */
                            userId: string;
                            /** @description owner | contributor */
                            role: string;
                            /**
                             * @description Author assignment date
                             * @example 2020-11-24T17:43:15.970Z
                             */
                            createdAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/authors/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/authors/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description New owner user id
                         */
                        newOwnerId: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Specifies a limit of returned records */
                    limit?: number;
                    /** @description Page number */
                    page?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Total number of items
                             * @example 5
                             */
                            count: number;
                            /**
                             * @description Number of items per page
                             * @example 10
                             */
                            limit: number;
                            /**
                             * @description Page number
                             * @example 0
                             */
                            page: number;
                            data: unknown[];
                        } & {
                            data: {
                                /** Format: uuid */
                                modelId: string;
                                /** Format: uuid */
                                userId: string;
                                /** @description owner | contributor */
                                role: string;
                                /**
                                 * @description Author assignment date
                                 * @example 2020-11-24T17:43:15.970Z
                                 */
                                createdAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            modelId: string;
                            /** Format: uuid */
                            granteeUserId: string;
                            /** @description read | write | admin */
                            permissionLevel: string;
                            /**
                             * @description Permission creation date
                             * @example 2020-11-24T17:43:15.970Z
                             */
                            createdAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description User to grant permission to
                         */
                        granteeUserId: string;
                        /** @description Permission level to grant */
                        permissionLevel: "read" | "write" | "admin";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            modelId: string;
                            /** Format: uuid */
                            granteeUserId: string;
                            /** @description read | write | admin */
                            permissionLevel: string;
                            /**
                             * @description Permission creation date
                             * @example 2020-11-24T17:43:15.970Z
                             */
                            createdAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/permissions/{granteeUserId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    granteeUserId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Specifies a limit of returned records */
                    limit?: number;
                    /** @description Page number */
                    page?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Total number of items
                             * @example 5
                             */
                            count: number;
                            /**
                             * @description Number of items per page
                             * @example 10
                             */
                            limit: number;
                            /**
                             * @description Page number
                             * @example 0
                             */
                            page: number;
                            data: unknown[];
                        } & {
                            data: ({
                                /**
                                 * Format: uuid
                                 * @description Entity's id
                                 * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                                 */
                                id: string;
                            } & {
                                /** Format: uuid */
                                modelId: string;
                                versionNumber: number;
                                title: string;
                                description: string | null;
                                /** Format: uuid */
                                nlogoxFileId: string;
                                netlogoVersion: string | null;
                                infoTab: string | null;
                                /** Format: date-time */
                                createdAt: string;
                                isFinalized: boolean;
                            })[];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Entity's id
                             * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                             */
                            id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/versions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/models/{id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Entity's id
                             * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                             */
                            id: string;
                        } & {
                            /** Format: uuid */
                            modelId: string;
                            versionNumber: number;
                            title: string;
                            description: string | null;
                            /** Format: uuid */
                            nlogoxFileId: string;
                            netlogoVersion: string | null;
                            infoTab: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            isFinalized: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Tag name to apply */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            modelVersionId: string;
                            /** Format: uuid */
                            tagId: string;
                            tagName: string;
                            /** Format: date-time */
                            createdAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/versions/{version}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    version: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Tag id
                             * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                             */
                            id: string;
                            /**
                             * @description Tag name
                             * @example climate
                             */
                            name: string;
                            /**
                             * @description Tag creation date
                             * @example 2020-11-24T17:43:15.970Z
                             */
                            createdAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Specifies a limit of returned records */
                    limit?: number;
                    /** @description Page number */
                    page?: number;
                    /** @description Tag name prefix for autocomplete */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Total number of items
                             * @example 5
                             */
                            count: number;
                            /**
                             * @description Number of items per page
                             * @example 10
                             */
                            limit: number;
                            /**
                             * @description Page number
                             * @example 0
                             */
                            page: number;
                            data: unknown[];
                        } & {
                            data: {
                                /**
                                 * Format: uuid
                                 * @description Tag id
                                 * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                                 */
                                id: string;
                                /**
                                 * @description Tag name
                                 * @example climate
                                 */
                                name: string;
                                /**
                                 * @description Tag creation date
                                 * @example 2020-11-24T17:43:15.970Z
                                 */
                                createdAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{idOrName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Tag UUID or case-insensitive name */
                    idOrName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Tag id
                             * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                             */
                            id: string;
                            /**
                             * @description Tag name
                             * @example climate
                             */
                            name: string;
                            /**
                             * @description Tag creation date
                             * @example 2020-11-24T17:43:15.970Z
                             */
                            createdAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": ({
                            /**
                             * Format: uuid
                             * @description Entity's id
                             * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                             */
                            id: string;
                        } & {
                            /**
                             * @description Entity creation date
                             * @example 2020-11-24T17:43:15.970Z
                             */
                            createdAt: string;
                            /**
                             * @description Entity last update date
                             * @example 2020-11-24T17:43:15.970Z
                             */
                            updatedAt: string;
                        }) & {
                            name: string | null;
                            email: string | null;
                            /** @description Indicates whether the user has verified their email address */
                            emailVerified: boolean;
                            image: string | null;
                            /** @description admin | moderator | user */
                            systemRole: string;
                            /** @description student | teacher | researcher | other */
                            userKind: string;
                            isProfilePublic: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Soft delete a user. Users can only delete their own account, except admins who can delete any account. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Update user profile. Users can only update their own profile, except admins who can update any profile. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        userKind?: "student" | "teacher" | "researcher" | "other";
                        isProfilePublic?: boolean;
                        systemRole?: "admin" | "moderator" | "user";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Specifies a limit of returned records */
                    limit?: number;
                    /** @description Page number */
                    page?: number;
                    /** @description student | teacher | researcher | other */
                    userKind?: "student" | "teacher" | "researcher" | "other";
                    /** @description admin | moderator | user */
                    systemRole?: "admin" | "moderator" | "user";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Total number of items
                             * @example 5
                             */
                            count: number;
                            /**
                             * @description Number of items per page
                             * @example 10
                             */
                            limit: number;
                            /**
                             * @description Page number
                             * @example 0
                             */
                            page: number;
                            data: unknown[];
                        } & {
                            data: (({
                                /**
                                 * Format: uuid
                                 * @description Entity's id
                                 * @example 2cdc8ab1-6d50-49cc-ba14-54e4ac7ec231
                                 */
                                id: string;
                            } & {
                                /**
                                 * @description Entity creation date
                                 * @example 2020-11-24T17:43:15.970Z
                                 */
                                createdAt: string;
                                /**
                                 * @description Entity last update date
                                 * @example 2020-11-24T17:43:15.970Z
                                 */
                                updatedAt: string;
                            }) & {
                                name: string | null;
                                email: string | null;
                                /** @description Indicates whether the user has verified their email address */
                                emailVerified: boolean;
                                image: string | null;
                                /** @description admin | moderator | user */
                                systemRole: string;
                                /** @description student | teacher | researcher | other */
                                userKind: string;
                                isProfilePublic: boolean;
                            })[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health Check Succeeded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
                /** @description Error Performing Health Check */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message for failure during health check
                             * @example Internal Server Error
                             */
                            message?: string;
                            /**
                             * @description Code representing the error. Always matches the HTTP response code.
                             * @example 500
                             */
                            statusCode?: number;
                        };
                    };
                };
                /** @description Health Check Failed */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error code associated with the failing check
                             * @example FST_UNDER_PRESSURE
                             */
                            code?: string;
                            /**
                             * @description Error thrown during health check
                             * @example Service Unavailable
                             */
                            error?: string;
                            /**
                             * @description Error message to explain health check failure
                             * @example Service Unavailable
                             */
                            message?: string;
                            /**
                             * @description Code representing the error. Always matches the HTTP response code.
                             * @example 503
                             */
                            statusCode?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorResponse */
        "def-0": {
            /** @example 400 */
            statusCode: number;
            /** @example Validation Error */
            message: string;
            /** @example Bad Request */
            error: string;
            /** @example YevPQs */
            correlationId: string;
            /**
             * @description Optional list of sub-errors
             * @example incorrect email
             */
            subErrors?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
