import type { UserSeed } from './types.js';

export const USERS: UserSeed[] = [
  {
    key: 'uri',
    legacyId: 1,
    name: 'Uri Wilensky',
    email: 'uri@example.com',
    userKind: 'researcher',
    isProfilePublic: true,
    affiliation:
      'Center for Connected Learning and Computer-Based Modeling, Northwestern University',
    country: 'US',
    bio: 'Creator of NetLogo. Researching agent-based modeling and complexity in education for two decades.',
    socialLinks: [
      { rawValue: 'https://ccl.northwestern.edu', type: 'website' },
      { rawValue: 'uri_wilensky', type: 'twitter' },
    ],
    createdDaysAgo: 900,
    devSession: true,
  },
  {
    key: 'seth',
    legacyId: 2,
    name: 'Seth Tisue',
    email: 'seth@example.com',
    userKind: 'researcher',
    isProfilePublic: true,
    affiliation: 'NetLogo Team, Northwestern University',
    country: 'US',
    bio: 'Maintainer and engineer on the NetLogo platform. Scala and functional programming enthusiast.',
    socialLinks: [{ rawValue: 'SethTisue', type: 'github' }],
    createdDaysAgo: 820,
    devSession: true,
  },
  {
    key: 'maria',
    name: 'Maria Hernández',
    email: 'maria@example.com',
    userKind: 'researcher',
    isProfilePublic: true,
    affiliation: 'Santa Fe Institute',
    country: 'ES',
    bio: 'Complexity scientist studying emergence in ecological and social systems.',
    socialLinks: [
      { rawValue: 'maria-hernandez', type: 'linkedin' },
      { rawValue: 'mh_complexity', type: 'twitter' },
    ],
    dob: '1985-04-12',
    createdDaysAgo: 540,
  },
  {
    key: 'kenji',
    name: 'Kenji Watanabe',
    email: 'kenji@example.com',
    userKind: 'teacher',
    isProfilePublic: true,
    affiliation: 'Tokyo Metropolitan High School',
    country: 'JP',
    bio: 'High-school physics teacher using NetLogo to teach emergence and systems thinking.',
    createdDaysAgo: 410,
  },
  {
    key: 'amara',
    name: 'Amara Okafor',
    email: 'amara@example.com',
    userKind: 'researcher',
    isProfilePublic: true,
    affiliation: 'University of Lagos, Department of Epidemiology',
    country: 'NG',
    bio: 'Epidemiologist modeling disease spread on contact networks.',
    socialLinks: [{ rawValue: 'amaraokafor', type: 'github' }],
    createdDaysAgo: 360,
  },
  {
    key: 'liam',
    name: 'Liam O’Connor',
    email: 'liam@example.com',
    userKind: 'teacher',
    isProfilePublic: true,
    affiliation: 'Trinity College Dublin',
    country: 'IE',
    bio: 'Lecturer in computational social science.',
    createdDaysAgo: 300,
  },
  {
    key: 'priya',
    name: 'Priya Nair',
    email: 'priya@example.com',
    userKind: 'researcher',
    isProfilePublic: true,
    affiliation: 'Indian Institute of Science, Bangalore',
    country: 'IN',
    bio: 'Studying swarm intelligence and collective animal behavior.',
    socialLinks: [{ rawValue: 'priya_nair', type: 'twitter' }],
    createdDaysAgo: 280,
  },
  {
    key: 'diego',
    name: 'Diego Fernández',
    email: 'diego@example.com',
    userKind: 'student',
    isProfilePublic: true,
    affiliation: 'Universidad de Buenos Aires',
    country: 'AR',
    bio: 'Grad student exploring traffic and urban dynamics models.',
    createdDaysAgo: 200,
  },
  {
    key: 'sophie',
    name: 'Sophie Laurent',
    email: 'sophie@example.com',
    userKind: 'student',
    isProfilePublic: false,
    affiliation: 'Sorbonne Université',
    country: 'FR',
    createdDaysAgo: 150,
  },
  {
    key: 'noah',
    name: 'Noah Schmidt',
    email: 'noah@example.com',
    userKind: 'student',
    isProfilePublic: false,
    country: 'DE',
    onboarded: false,
    emailVerified: false,
    createdDaysAgo: 30,
  },
  {
    key: 'fatima',
    name: 'Fatima Al-Sayed',
    email: 'fatima@example.com',
    userKind: 'teacher',
    isProfilePublic: true,
    affiliation: 'American University of Beirut',
    country: 'LB',
    bio: 'Teaching introductory modeling to undergraduates.',
    createdDaysAgo: 120,
  },
  {
    key: 'chen',
    name: 'Chen Wei',
    email: 'chen@example.com',
    userKind: 'researcher',
    isProfilePublic: true,
    affiliation: 'Tsinghua University',
    country: 'CN',
    bio: 'Economist interested in agent-based models of markets and wealth distribution.',
    createdDaysAgo: 95,
  },
  {
    key: 'mod-grace',
    legacyId: 47,
    name: 'Grace Mwangi',
    email: 'grace@example.com',
    systemRole: 'moderator',
    userKind: 'other',
    isProfilePublic: true,
    affiliation: 'Modeling Commons',
    country: 'KE',
    bio: 'Community moderator keeping the commons tidy.',
    createdDaysAgo: 600,
    devSession: true,
  },
  {
    key: 'admin',
    legacyId: 99,
    name: 'Site Admin',
    email: 'admin@example.com',
    systemRole: 'admin',
    userKind: 'other',
    isProfilePublic: false,
    affiliation: 'Modeling Commons',
    createdDaysAgo: 1000,
    devSession: true,
  },
];
