name: Setup Helio
description: Sets up Node.js, installs dependencies, and configures SSH for deployment

inputs:
  ssh-private-key:
    description: The SSH private key to use for authentication
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js and dependencies
      uses: ./.github/actions/setup-node-deps

    - name: Setup SSH
      uses: ./.github/actions/setup-ssh
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
