server {
  listen 8080;

  root /opt/galapagos/target/play-scrape;
  index index.html;

  location / {
    try_files $uri $uri/ $uri.html $uri/index.html =404;
  }

  location /web {
    if ($arg_url ~* ^(https?://)(127\.0\.0\.1|localhost)(.*)$) {
      return 302 $scheme://$host:$server_port$uri?url=$1host.docker.internal$3;
    }

    try_files $uri $uri/ $uri.html $uri/index.html =404;
  }
}
