name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Run ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: [check-types, lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --ignore-scripts

      - name: Build Packages
        run: |
          yarn run build
          yarn install --force

      - name: Run ${{ matrix.command }}
        run: yarn ${{ matrix.command }}
