name: Deploy docs.netlogo.org

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted-linux
    name: Deploy documentation site

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helio
        uses: ./.github/actions/setup-helio
        with:
          ssh-private-key: ${{ secrets.DOCS_DEPLOY_PRIVATE_KEY }}

      - name: Build and deploy
        working-directory: apps/docs
        shell: bash
        env:
          HELIO_HEADLESS: 1
          HELIO_SKIP_CHECKS: 1
          NUXT_TELEMETRY_DISABLED: 1
        run: yarn run docs:deploy
